import { v4 as uuid } from 'uuid'; 

const clientsData = [
  {
    client_id: uuid(),
    nin: '123456789',
    first_name: 'Oketch',
    last_name: 'James',
    price: 5,
    email: 'oketch@gmail.com',
    payment_status: true,
    assigned_employee: 'Fungaroo',
    enrolled_courses: 'DA1',
    phone_number: '0789456123',
    status: 'Registered',
  },
  {
    client_id: uuid(),
    nin: '123456789',
    first_name: 'Oketch',
    last_name: 'James',
    price: 5,
    email: 'oketch@gmail.com',
    payment_status: true,
    assigned_employee: 'Fungaroo',
    enrolled_courses: 'DA1',
    phone_number: '0789456123',
    status: 'Registered',
  },
  {
    client_id: uuid(),
    nin: '123456789',
    first_name: 'Oketch',
    last_name: 'James',
    price: 5,
    email: 'oketch@gmail.com',
    payment_status: true,
    assigned_employee: 'Fungaroo',
    enrolled_courses: 'DA1',
    phone_number: '0789456123',
    status: 'Registered',
  },
  {
    client_id: uuid(),
    nin: '123456789',
    first_name: 'Oketch',
    last_name: 'James',
    price: 5,
    email: 'oketch@gmail.com',
    payment_status: true,
    assigned_employee: 'Fungaroo',
    enrolled_courses: 'DA1',
    phone_number: '0789456123',
    status: 'Registered',
  },
  {
    client_id: uuid(),
    nin: '123456789',
    first_name: 'Oketch',
    last_name: 'James',
    price: 5,
    email: 'oketch@gmail.com',
    payment_status: true,
    assigned_employee: 'Fungaroo',
    enrolled_courses: 'DA1',
    phone_number: '0789456123',
    status: 'Registered',
  },
  {
    client_id: uuid(),
    nin: '123456789',
    first_name: 'Oketch',
    last_name: 'James',
    price: 5,
    email: 'oketch@gmail.com',
    payment_status: true,
    assigned_employee: 'Fungaroo',
    enrolled_courses: 'DA1',
    phone_number: '0789456123',
    status: 'Registered',
  },
  {
    client_id: uuid(),
    nin: '123456789',
    first_name: 'Oketch',
    last_name: 'James',
    price: 5,
    email: 'oketch@gmail.com',
    payment_status: true,
    assigned_employee: 'Fungaroo',
    enrolled_courses: 'DA1',
    phone_number: '0789456123',
    status: 'Registered',
  },
  {
    client_id: uuid(),
    nin: '123456789',
    first_name: 'Oketch',
    last_name: 'James',
    price: 5,
    email: 'oketch@gmail.com',
    payment_status: true,
    assigned_employee: 'Fungaroo',
    enrolled_courses: 'DA1',
    phone_number: '0789456123',
    status: 'Registered',
  },
  {
    client_id: uuid(),
    nin: '123456789',
    first_name: 'Oketch',
    last_name: 'James',
    price: 5,
    email: 'oketch@gmail.com',
    payment_status: true,
    assigned_employee: 'Fungaroo',
    enrolled_courses: 'DA1',
    phone_number: '0789456123',
    status: 'Registered',
  },
  {
    client_id: uuid(),
    nin: '123456789',
    first_name: 'Oketch',
    last_name: 'James',
    price: 5,
    email: 'oketch@gmail.com',
    payment_status: true,
    assigned_employee: 'Fungaroo',
    enrolled_courses: 'DA1',
    phone_number: '0789456123',
    status: 'Registered',
  },
  {
    client_id: uuid(),
    nin: '123456789',
    first_name: 'Oketch',
    last_name: 'James',
    price: 5,
    email: 'oketch@gmail.com',
    payment_status: true,
    assigned_employee: 'Fungaroo',
    enrolled_courses: 'DA1',
    phone_number: '0789456123',
    status: 'Registered',
  },
  {
    client_id: uuid(),
    nin: '123456789',
    first_name: 'Oketch',
    last_name: 'James',
    price: 5,
    email: 'oketch@gmail.com',
    payment_status: true,
    assigned_employee: 'Fungaroo',
    enrolled_courses: 'DA1',
    phone_number: '0789456123',
    status: 'Registered',
  },
];

export default clientsData;
